//! `sinorag agent` — launch opencode with the SinoRAG MCP server pre-wired.
//!
//! The agent subcommand is a thin launcher:
//!   1. Resolve the runtime workdir.
//!   2. Resolve the opencode binary (flag → env → PATH).
//!   3. Refresh `<workdir>/.opencode/opencode.json` pointing opencode at
//!      `<this exe> mcp ...` (path resolved via `std::env::current_exe`).
//!   4. Refresh `<workdir>/AGENTS.md` from embedded doctrine.
//!   5. Exec opencode with that working directory.
//!
//! Single binary, no separate server process for the user to manage.

pub mod doctrine;

use std::path::PathBuf;
use std::process::Command;

use anyhow::{anyhow, Context, Result};
use serde_json::json;

pub struct AgentArgs {
    pub opencode: Option<PathBuf>,
    pub pack: Option<PathBuf>,
    pub allow_admin_tools: bool,
    pub writable: bool,
    pub output_root: Option<PathBuf>,
    pub dry_run: bool,
}

const AGENTS_MD_MANAGED_BODY: &str = include_str!("doctrine/agents_md.md");
const SENTINEL_BEGIN: &str =
    "<!-- BEGIN sinorag-managed: doctrine block (regenerated by `sinorag agent`) -->";
const SENTINEL_END: &str = "<!-- END sinorag-managed -->";

pub fn run(args: AgentArgs) -> Result<()> {
    // `main.rs` already chdir's into the exe's directory at startup so the
    // binary works the same regardless of where it was invoked. That's where
    // the bundled `data/` pack lives, so it's also the right workdir for
    // opencode — no flag needed.
    let workdir = resolve_workdir()?;
    let self_exe = std::env::current_exe()
        .context("failed to resolve current_exe for MCP launcher")?
        .canonicalize()
        .context("failed to canonicalize current_exe")?;
    let self_exe = strip_extended_prefix(self_exe);

    write_opencode_config(
        &workdir,
        &self_exe,
        args.pack.as_deref(),
        args.allow_admin_tools,
        args.writable,
        args.output_root.as_deref(),
    )?;
    write_agents_md(&workdir)?;

    if args.dry_run {
        eprintln!(
            "agent: dry-run wrote {}/.opencode/opencode.json and AGENTS.md",
            workdir.display()
        );
        return Ok(());
    }

    let opencode = resolve_opencode(args.opencode)?;
    eprintln!(
        "agent: launching {} in {}",
        opencode.display(),
        workdir.display()
    );

    let status = Command::new(&opencode)
        .current_dir(&workdir)
        .status()
        .with_context(|| format!("failed to spawn opencode at {}", opencode.display()))?;
    if !status.success() {
        return Err(anyhow!("opencode exited with status {status}"));
    }
    Ok(())
}

fn resolve_workdir() -> Result<PathBuf> {
    let dir = std::env::current_dir().context("failed to read current directory")?;
    let abs = dir
        .canonicalize()
        .with_context(|| format!("failed to canonicalize workdir {}", dir.display()))?;
    Ok(strip_extended_prefix(abs))
}

/// On Windows, `canonicalize` returns extended-length paths prefixed with
/// `\\?\`. Many cross-platform tools (opencode included) choke on that form;
/// strip it back to a plain path when it's safe to do so.
fn strip_extended_prefix(p: PathBuf) -> PathBuf {
    #[cfg(windows)]
    {
        let s = p.to_string_lossy();
        if let Some(rest) = s.strip_prefix(r"\\?\") {
            // Don't strip the prefix off a UNC path (`\\?\UNC\server\share`):
            // dropping it would yield a malformed path.
            if !rest.starts_with("UNC\\") {
                return PathBuf::from(rest);
            }
        }
    }
    p
}

fn resolve_opencode(flag: Option<PathBuf>) -> Result<PathBuf> {
    crate::which::resolve_binary(flag.as_deref(), "OPENCODE_BIN", "opencode").ok_or_else(|| {
        anyhow!(
            "could not locate opencode binary. Pass --opencode <path>, \
                 set $OPENCODE_BIN, or install opencode on PATH. \
                 Run `sinorag setup opencode` for diagnostics."
        )
    })
}

fn write_opencode_config(
    workdir: &std::path::Path,
    self_exe: &std::path::Path,
    pack: Option<&std::path::Path>,
    allow_admin_tools: bool,
    writable: bool,
    output_root: Option<&std::path::Path>,
) -> Result<()> {
    let dir = workdir.join(".opencode");
    std::fs::create_dir_all(&dir).with_context(|| format!("failed to create {}", dir.display()))?;

    let mut command = vec![self_exe.to_string_lossy().into_owned(), "mcp".to_string()];
    if let Some(p) = pack {
        command.push("--pack".to_string());
        command.push(p.to_string_lossy().into_owned());
    }
    if allow_admin_tools {
        command.push("--allow-admin-tools".to_string());
    }
    if writable {
        command.push("--writable".to_string());
    }
    if let Some(root) = output_root {
        command.push("--output-root".to_string());
        command.push(root.to_string_lossy().into_owned());
    }

    let config = json!({
        "$schema": "https://opencode.ai/config.json",
        "mcp": {
            "sinorag": {
                "type": "local",
                "command": command,
                "enabled": true
            }
        }
    });

    let path = dir.join("opencode.json");
    let text = serde_json::to_string_pretty(&config)?;
    std::fs::write(&path, text).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

/// Refresh the sinorag-managed slice of `AGENTS.md` without clobbering any
/// user-authored content surrounding it. The managed slice is delimited by
/// HTML-comment sentinels; on each launch we replace what's between them.
fn write_agents_md(workdir: &std::path::Path) -> Result<()> {
    let path = workdir.join("AGENTS.md");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let new_contents = update_managed_block(&existing);
    std::fs::write(&path, new_contents)
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

fn update_managed_block(existing: &str) -> String {
    let managed = format!(
        "{}\n{}\n{}",
        SENTINEL_BEGIN,
        AGENTS_MD_MANAGED_BODY.trim_end(),
        SENTINEL_END,
    );

    match (existing.find(SENTINEL_BEGIN), existing.find(SENTINEL_END)) {
        (Some(start), Some(end)) if end > start => {
            // Replace the existing managed slice (and the line break right
            // after the END sentinel, if any) with the regenerated block.
            let end_of_sentinel = end + SENTINEL_END.len();
            let mut out = String::with_capacity(existing.len() + managed.len());
            out.push_str(&existing[..start]);
            out.push_str(&managed);
            out.push_str(&existing[end_of_sentinel..]);
            out
        }
        _ if existing.trim().is_empty() => format!("{managed}\n"),
        _ => {
            // User has their own AGENTS.md but no sentinels — prepend the
            // managed block so opencode sees it first; user content stays
            // intact below.
            format!("{managed}\n\n{existing}")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_block_into_empty_file() {
        let out = update_managed_block("");
        assert!(out.contains(SENTINEL_BEGIN));
        assert!(out.contains(SENTINEL_END));
    }

    #[test]
    fn prepends_block_when_user_content_has_no_sentinels() {
        let out = update_managed_block("# My notes\n\nhello\n");
        assert!(out.starts_with(SENTINEL_BEGIN));
        assert!(out.contains("# My notes"));
    }

    #[test]
    fn replaces_only_the_managed_slice() {
        let prior =
            format!("# Above\n\n{SENTINEL_BEGIN}\nold managed body\n{SENTINEL_END}\n\n# Below\n");
        let out = update_managed_block(&prior);
        assert!(out.contains("# Above"));
        assert!(out.contains("# Below"));
        assert!(!out.contains("old managed body"));
        assert!(out.contains("SinoRAG Research Agent"));
    }
}
